"""Training script generator for Llama fine-tuning on swarm-gpu.

Generates a ready-to-run Python training script using Unsloth + SFTTrainer
configured for the NVIDIA L4 GPU on swarm-gpu. Based on the proven setup
that completed 120 steps in 7m 8s.
"""

from sqlmodel import Session, select, func
from backend.models import ConversationTurn

RECOMMENDED_MIN_TURNS = 5000


def check_readiness(session: Session) -> dict:
    """Check if we have enough data to fine-tune."""
    total = session.exec(
        select(func.count(ConversationTurn.id))
    ).one()

    exportable = session.exec(
        select(func.count(ConversationTurn.id)).where(
            ConversationTurn.output_tokens >= 50
        )
    ).one()

    return {
        "total_turns": total,
        "exportable": exportable,
        "recommended_min": RECOMMENDED_MIN_TURNS,
        "ready": exportable >= RECOMMENDED_MIN_TURNS,
    }


def generate_training_script(
    data_path: str = "training_data.jsonl",
    output_dir: str = "lora_model",
    max_steps: int = 500,
    learning_rate: float = 2e-4,
    batch_size: int = 2,
    gradient_accumulation: int = 4,
    max_seq_length: int = 2048,
) -> str:
    """Generate a Python training script for Unsloth LoRA fine-tuning.

    Returns the full script as a string, ready to be saved and executed
    on swarm-gpu.
    """
    return f'''"""Fine-tune Llama 3.1 8B with LoRA using Unsloth.

Auto-generated by AI Portal distillation module.
Run on swarm-gpu (NVIDIA L4 GPU).

Usage:
    python train_distilled.py
"""

import json
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments
from datasets import Dataset

# ── Configuration ──────────────────────────────────────────────
MODEL_NAME = "unsloth/Meta-Llama-3.1-8B-bnb-4bit"
DATA_PATH = "{data_path}"
OUTPUT_DIR = "{output_dir}"
MAX_SEQ_LENGTH = {max_seq_length}
MAX_STEPS = {max_steps}
LEARNING_RATE = {learning_rate}
BATCH_SIZE = {batch_size}
GRADIENT_ACCUMULATION = {gradient_accumulation}

# ── Load model ─────────────────────────────────────────────────
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_NAME,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,  # auto-detect
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

# ── Load dataset ───────────────────────────────────────────────
records = []
with open(DATA_PATH, "r") as f:
    for line in f:
        line = line.strip()
        if line:
            records.append(json.loads(line))

print(f"Loaded {{len(records)}} training examples from {{DATA_PATH}}")

# Format as Alpaca prompts
ALPACA_TEMPLATE = """Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{{instruction}}

### Input:
{{input}}

### Response:
{{output}}"""

def format_example(example):
    return ALPACA_TEMPLATE.format(
        instruction=example.get("instruction", "You are a helpful AI assistant."),
        input=example.get("input", ""),
        output=example.get("output", ""),
    )

formatted = [format_example(r) for r in records]
dataset = Dataset.from_dict({{"text": formatted}})

# ── Train ──────────────────────────────────────────────────────
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    formatting_func=lambda x: x["text"],
    args=TrainingArguments(
        output_dir=OUTPUT_DIR,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION,
        warmup_steps=5,
        max_steps=MAX_STEPS,
        learning_rate=LEARNING_RATE,
        fp16=True,
        logging_steps=10,
        save_steps=100,
        optim="adamw_8bit",
        seed=3407,
    ),
)

print("Starting training...")
trainer.train()

# ── Save ───────────────────────────────────────────────────────
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"LoRA adapter saved to {{OUTPUT_DIR}}/")
'''


def get_training_instructions(readiness: dict) -> dict:
    """Return step-by-step instructions for running fine-tuning."""
    script = generate_training_script()

    steps = [
        "1. Export training data: visit Usage > Training Data tab and click 'Export JSONL'",
        "2. Copy data to swarm-gpu: scp training_data.jsonl Crypt@<swarm-gpu-ip>:~/",
        "3. Save the training script below as ~/train_distilled.py on swarm-gpu",
        "4. Run: python3 train_distilled.py",
        "5. After training completes, serve with vLLM or Ollama:",
        "   vllm serve ~/lora_model --host 0.0.0.0 --port 8080",
        "   OR: ollama create distilled -f ~/lora_model/Modelfile && ollama serve",
        "6. Set LOCAL_LLAMA_BASE_URL=http://<swarm-gpu-ip>:8080/v1 in Portal .env",
    ]

    return {
        "ready": readiness["ready"],
        "turn_count": readiness["total_turns"],
        "exportable": readiness["exportable"],
        "recommended_min": readiness["recommended_min"],
        "instructions": steps,
        "training_script": script,
    }
